services:

  mysql:
    image: mysql:8.0
    container_name: codearena-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: codearena

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/codearena_full.sql:/docker-entrypoint-initdb.d/codearena_full.sql

  backend:
    build:
      context: ./backend

    container_name: codearena-backend

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/codearena
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend

    container_name: codearena-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  mysql_data: